name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: test
      - run: make integration_test
  build:
    runs-on: ubuntu-latest
    needs:
      - integration_test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: public.ecr.aws/cookpad/itacho
          tags: |
            type=sha,prefix=,format=long
            type=ref,event=tag
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        if: github.event_name == 'push'
      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
        if: github.event_name == 'push'
      - uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
